### PR TITLE
Fix tutorial. Support exporting network when device is not cuda.

### PR DESCRIPTION
**Pull request by itrendafilov**

### CODE REVIEW

**Comment by mgkwill** [comment]
Hi @itrendafilov thanks for this PR!

Generally we require an issue to be filed for each PR that explains the issue.

I'm running CI on your change and I've added @bamsumit to review.

**Comment by bamsumit** [comment]
Hi @itrendafilov thanks for your pull request. It looks like you skipped running the training part of the notebook and directly tried to load the trained torch model. That's why you are facing the issue. The exported hdf5 file is already there, so the fix is not required anyway.

If you want to load the network from the saved torch model, then yes what you are doing is the correct way to do it. But that is not the point of the tutorial.

**Comment by itrendafilov** [comment]
Hi @bamsumit, I was running all steps in the tutorial. The problem is that by default the torch.load() is using map_location that is looking for a cuda device. If you don't have an nVidia GPU in your system, this throws an exception.

**Comment by bamsumit** [comment]
@itrendafilov are you sure you ran the training for more than 10 epochs? The code will only save the network at epoch=11 and it takes a lot of time for CPU training to reach there.

**Comment by bamsumit** [comment]
@itrendafilov, an acceptable solution is to change 
```python
if scheduler.snn_stat.best_accuracy:
    ...
```
to 
```python
if scheduler.snn_stat.best_accuracy or epoch==0:
    ...
```
in **Training Loop** block. This would save the model on the first epoch and load the trained model later.

**Comment by itrendafilov** [comment]
@bamsumit  Sorry for the delayed reply. Yes, I was running with epoch=10 when I had observed the issue.  I just retested everything after a git hard reset. I haven't changed any code this time (beside enabling cpu), and it works without any exceptions. I suppose we can close the merge request. Do you want me to do that?

**Comment by bamsumit** [comment]
@itrendafilov, thanks for letting us know it is working now. I'll close this request now.

**Pull request closed without merging**
