### PR TITLE
Add missing __init__.py files

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Review by mgkwill — COMMENTED** [review]
@Tobias-Fischer  Thanks for the pull request. I believe both of these are not present to prevent namespace clash. @bamsumit @srrisbud  

See https://github.com/lava-nc/lava-optimization/pull/12
and more discussion at:
https://github.com/lava-nc/lava/issues/64

**Comment by bamsumit** [comment]
The namespace `lava.lib` is going to exist in all of our lava libraries. If we have `__init__.py` at this level, we will have module clash across libraries. So there should be no `__init__.py` in `src/lava/lib`.

The intended mode of use is
```
import lava  # this should import the lava-core, not the libararies
from lava.lib.dl import slayer, bootstrap
from lava.lib import optimizaton  # and so on
```

**Comment by awintel** [comment]
Isn't that why @srrisbud  introduced the namespace packages. We should use the same mechanism across all packages to define shared namespaces and avoid clashes.

**Comment by bamsumit** [comment]
@awintel I think you are referring to

```
__import__("pkg_resources").declare_namespace(__name__) 
```

As far as I understand, this is taken care of by implicit namespace since python 3.3. The [PEP 420](https://www.python.org/dev/peps/pep-0420/) guideline is to have empty `__init__.py` to declare a module at that level, and no `__init__.py` to allow namespace search instead. We can still customize imports by customizing `__all__` variable in `__init__.py`

**Comment by awintel** [comment]
Yes, implicit namesspaces are nice thing if you need no init.py which is generally not true. Often you want init.py to simplify imports (not only to restrict imports with __all__). 
All I was suggesting is to use a consistent way of defining names spaces throughout the whole repo. And because implicit namesspaces without init.py are generally disadvantageous if you need an init.py I don't prefer them.

**Comment by Tobias-Fischer** [comment]
Hi - to give you a bit more background information. I am planning to add Lava to conda-forge so that Lava can be easily installed using conda (I use it all the time ..). I added a pull request there: https://github.com/conda-forge/staged-recipes/pull/16952 - please let me know if any if you want to become a maintainer of the feedstock, too.

`pybuilder` doesn't seem to work well there (it doesn't find the packages installed via conda and tries to install stuff via pip which is not compatible). So instead I've written a simple `setup.py` that uses `setuptools`:
```python
import os
from setuptools import setup, find_packages

from build import version, name, summary, url

setup(
    name = name,
    version = version,
    author = "Lava Project",
    description = summary,
    url = url,
    packages=find_packages(where='src'),
    package_dir={"": "src"},
)
```

The call to `find_packages` does not find any packages if no `__init__.py` is present (as proposed here in the PR).

Note that the conda packages can be installed (and imported) side-by-side (i.e. lava-dl and lava-optimization) without any namespace issues.

Happy to discuss about this elsewhere. I've never used pybuilder before so I don't need what tweaks it needs. Adding directories to `PYTHONPATH` should generally be avoided - that's what `pip install -e .` is there for in my opinion.

**Comment by bamsumit** [comment]
Hi @Tobias-Fischer can you try this setup.py script instead?

```python
import os
from setuptools import setup, find_namespace_packages

from build import version, name, summary, url

setup(
    name = name,
    version = version,
    author = "Lava Project",
    description = summary,
    url = url,
    packages = find_namespace_packages(include=['lava.*'], where='src'),
    package_dir={"": "src"},
)
```

**Comment by Tobias-Fischer** [comment]
Yes that works - thanks!

**Pull request closed without merging**
