### PR TITLE
Added XOR-Regression tutorial.

### PR DESCRIPTION
**Pull request by ahenkes1**
Objective of pull request:

I wrote a simple, minimalistic regression tutorial using the lava-dl framework. It consists of optional installation instructions for Google Colab, such that everybody can directly dive into it without problems! A simple XOR task is solved using a small CUBA network. Despite being a toy example, this tutorial can aid as a basis for LAVA-DL beginners interested in regression tasks. Important keywords are linked to further resources. 

## Pull request checklist

Your PR fulfills the following requirements:
- [ ] [Issue](https://github.com/lava-nc/lava-dl/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [ x] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ x] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [x ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [x ] Build tests (`pytest`) passes locally

## Pull request type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [x ] Other (please describe): Tutorial

## Does this introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Review by bamsumit — CHANGES_REQUESTED** [review]
Thanks @ahenkes1  for the contribution. This looks good overall. I especially like the thorough description :).  Here are few of my comments.

1. Please get rid of this installation cell.
image

2. How about using a classifier instead of None. This is a classification problem. It would be good to see the accuracy.
image

**Comment by timcheck** [comment]
Thanks @ahenkes1, looks really nice. I agree with @bamsumit install instructions are already available [https://github.com/lava-nc/lava-dl/#windowsmacoslinux](https://github.com/lava-nc/lava-dl/#windowsmacoslinux), so should not be included in the tutorial itself.

You could also add your tutorial to the list of tutorials on [https://github.com/lava-nc/lava-dl#getting-started](https://github.com/lava-nc/lava-dl#getting-started).

**Comment by ahenkes1** [comment]
Hello @timcheck , @bamsumit , @PhilippPlank , is there still something to do here?

**Review by bamsumit — APPROVED** [review]
Looks good @ahenkes1 . Thank you for your contribution.

**Pull request merged**
